# config for shadow
CFG:
  DEBUG: false
  num_accessible_probs: 10 # match with accessible classes logits/probability classes number from the target model. usually top 5 for APIs
  num_epochs: 25 # number of shadow model train epochs
  val_acc_goal: -1 # shadow model's goal accuracy working as early stop. -1 for not using early stop
  num_shadow_models: 32
  shadow_train_size: 0.5 # fraction to divide CIFAR train dataset for shadow model training
  target_train_size: 0.8 # fraction to divide CIFAR test dataset for target model training
  seed: 42
  num_classes: 10 # CIFAR10 vs CIFAR100 selection
  learning_rate: 0.0005 # Efficientnet Learning rate
  weight_decay: 0.00005 # default lr: wd ratio is 0.1(https://github.com/clovaai/AdamP), but using 0.01 for small dataset
  input_resolution: 64
  train_batch_size: 1024
  val_batch_size: 1024
  logging_steps: 1000
  save_path: ./ckpt
  model_architecture: resnet18
  bool_pretrained: false
# config for attack model

CFG_ATTACK:
  attack_dset_path: ./attack/ResNet_pretrained_False_num_shadow_64.csv
  train_size: 100000
  test_size: 0.1
  n_estimators: 10000
  attack_model_path: ./attack/XGBClassifier.joblib
